logging:
  level:
    com:
      jqtianxia: debug
      baomidou: debug

spring:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/battery?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: "root"
    password: "root"
