server:
  port: 9056
spring: 
  thymeleaf:
    cache: false
  main:
    show-banner: false
    banner-mode: "off"
  application: 
    name: "riskwaste-adminapi"

  # dev 开发环境
  # test 测试环境
  # prod 生产环境
  profiles:
    active: "dev"
     
    
mybatis-plus:
  mapper-locations: classpath*:*/mapper/*.xml